import { Inter } from 'next/font/google'
import { mynavbar2 } from '../../../components/MyNavBar'
// import {Providers} from ".././providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Rizki',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className='dark'>
      {/* <body className={inter.className}><Providers>{children}</Providers></body> */}
      <body className={inter.className}>{mynavbar2} {children}</body>
      {/* <body className={inter.className}><BasicLayout>{children}</BasicLayout></body> */}
    </html>
  )
}
